-- Descriptors for the existing 52 recipes, drafted from each recipe's
-- ingredients and steps and approved by Anabelle (2026-10-06). Keyed on
-- name; a recipe renamed before this runs just keeps a null descriptor.
update public.recipes r
set descriptor = v.descriptor
from (values
  ('Basic, But Make It Lasagna', 'Classic beef and ricotta lasagna'),
  ('BBQ Ribs ’n’ Cauli Nuggets', 'BBQ pork ribs with crispy breaded cauliflower'),
  ('Berry Good Watermelon Salad', 'Watermelon, blueberry and feta salad with spinach'),
  ('Boursin-Me-Up Chicken & Mushroom Rice', 'Creamy garlic-herb chicken and mushrooms over rice'),
  ('Breakfast for Dinner — Eggy Croissant', 'Egg and cheddar croissant sandwiches'),
  ('Breakfast for Dinner — Froot Loops French Toasts', 'Cereal-crusted French toast with yogurt'),
  ('Catch of the Tray', 'Sheet-pan tilapia with roasted potatoes and carrots'),
  ('Cauli Mac & Cheese, Please', 'Mac and cheese with cauliflower and bacon'),
  ('Cheesy Whizzy Spaghetti', 'Spaghetti in a quick, creamy cheese sauce'),
  ('Chicken, Beans & Corny Things', 'Smoky chicken with beans, corn, kale and rice'),
  ('Coconut About Basa & Eggplant', 'Red curry basa with eggplant and rice'),
  ('Cold Cuts, Hot Pizza', 'Homemade deli meat and cheese pizza'),
  ('Cottage Pie, Meet Rutabaga', 'Beef cottage pie with potato and rutabaga mash'),
  ('Crack a Tin — Sardine Spaghetti', 'Spaghetti with sardines, garlic and spinach'),
  ('Curry Up Coconut Chicken', 'Coconut chicken curry'),
  ('Curry Up, It''s Vegan!', 'Tofu and chickpea coconut curry with rice'),
  ('Eggplant Got Beef', 'Garlicky beef and eggplant stir-fry with rice'),
  ('Fast Food Fakeout — Big Mac Combo', 'Double cheeseburgers with special sauce and fries'),
  ('Fish Sticks & Chill', 'Baked fish sticks and fries'),
  ('Fry Me a Sandwich', 'Cheesy fry sandwich with tangy slaw'),
  ('Honey Garlic Chicken Noodle Toss', 'Honey garlic chicken with broccoli and rice noodles'),
  ('Honey, I Glazed the Chicken', 'Honey-soy glazed drumsticks with broccoli'),
  ('Hot Dog Hash', 'Crispy potato and hot dog skillet'),
  ('Instant Noodles Forever — The Pork One', 'Ramen with pork belly and a soft egg'),
  ('Jamaican Patty with Mango Salsa & Caramelized Plantain', 'Beef patties with mango salsa, plantain and black beans'),
  ('K-Pogo (TikTok Korean Corn Dog)', 'Panko-crusted corn dogs with chip crumbs and cheese sauce'),
  ('Kielbasa Gone Krauty', 'Smoked kielbasa braised with sauerkraut'),
  ('Kraft Dinner alla Carbonara', 'Boxed mac and cheese, carbonara-style with bacon and peas'),
  ('Kraft Singles Mac ’n’ Mingle', 'Baked mac and cheese with turkey bacon'),
  ('Lamb Sweet Tagine', 'Lamb tagine with sweet potato and chickpeas'),
  ('Napolitan (Japanese Ketchup Spaghetti) ナポリタン', 'Spaghetti with sausage and peppers in a ketchup sauce'),
  ('Pizza à la Caesar', 'Frozen pizza topped with Caesar salad'),
  ('Pizza Party Pasta', 'Baked pepperoni pizza pasta'),
  ('Pork Yeah! Noodle Bowl', 'Hoisin pork and cabbage with rice noodles'),
  ('Porktoberfest', 'Roast pork loin with butternut squash and apples'),
  ('Potato, Bacon, Cheese, Repeat', 'Loaded baked potatoes with bacon and cheddar'),
  ('Salmon Says Fettuccine', 'Creamy salmon and spinach fettuccine'),
  ('Samosa Chaat', 'Samosas topped with yogurt, chutney and fresh veg'),
  ('Sizzling Pork Skewers', 'Pork kabobs with zucchini and rice'),
  ('Smoking Hot Sweet Potato & Kale Skillet', 'Smoked sausage with sweet potato and kale'),
  ('Souvlaki Street Bowl with a Kick', 'Chicken souvlaki rice bowl with peppers and feta'),
  ('Squash the Hunger Chili', 'Beef and kidney bean chili with squash'),
  ('Sticky Chicken, Crisp Apple', 'Honey-soy drumsticks with apple and cabbage slaw'),
  ('Sunday Roast With the Most', 'Roast chicken with potatoes and green beans'),
  ('Sundubu Jjigae (Spicy Soft Tofu Stew)', 'Spicy Korean soft tofu stew with pork belly'),
  ('Taco Tuesday, Every Day', 'Ground beef tacos with all the fixings'),
  ('Thanks, It’s Turkey', 'Roast turkey with mash, gravy and veg'),
  ('The Great Pepper Roast', 'Creamy roasted pepper and white bean soup'),
  ('TikTok Baked Feta Pasta (with a tofu twist)', 'Baked feta and cherry tomato pasta with tofu'),
  ('Tomato Soup & Grilled Cheese Remix', 'Cheesy tomato bread bake'),
  ('Vermicelli Gets a Spring Roll', 'Vermicelli bowl with spring rolls and fresh veg'),
  ('Wok This Way Hoisin Pork', 'Hoisin pork stir-fry with rice')
) as v(name, descriptor)
where r.name = v.name;
